// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBur9crsaM2qEIJcHO2Y81Yz2sbwfgz8xg',
    appId: '1:665376916406:web:061fed0bbf1e5bd9f17717',
    messagingSenderId: '665376916406',
    projectId: 'oipms-8c6aa',
    authDomain: 'oipms-8c6aa.firebaseapp.com',
    storageBucket: 'oipms-8c6aa.firebasestorage.app',
    measurementId: 'G-JRB91VQHMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA27WB3IV7tbfIFYokvi9rOJ5AiKAymKqY',
    appId: '1:665376916406:android:f3bd6ca42b498baaf17717',
    messagingSenderId: '665376916406',
    projectId: 'oipms-8c6aa',
    storageBucket: 'oipms-8c6aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4F1_2YKKgF-Z49nlQmXjtNe8ne6MKp8',
    appId: '1:665376916406:ios:8518b8d67b2384d1f17717',
    messagingSenderId: '665376916406',
    projectId: 'oipms-8c6aa',
    storageBucket: 'oipms-8c6aa.firebasestorage.app',
    iosClientId: '665376916406-hg3no3h2u0jt1imiit324adou30t9329.apps.googleusercontent.com',
    iosBundleId: 'com.example.oipSentinel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe4F1_2YKKgF-Z49nlQmXjtNe8ne6MKp8',
    appId: '1:665376916406:ios:8518b8d67b2384d1f17717',
    messagingSenderId: '665376916406',
    projectId: 'oipms-8c6aa',
    storageBucket: 'oipms-8c6aa.firebasestorage.app',
    iosClientId: '665376916406-hg3no3h2u0jt1imiit324adou30t9329.apps.googleusercontent.com',
    iosBundleId: 'com.example.oipSentinel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBur9crsaM2qEIJcHO2Y81Yz2sbwfgz8xg',
    appId: '1:665376916406:web:2178fb9a3f7564e7f17717',
    messagingSenderId: '665376916406',
    projectId: 'oipms-8c6aa',
    authDomain: 'oipms-8c6aa.firebaseapp.com',
    storageBucket: 'oipms-8c6aa.firebasestorage.app',
    measurementId: 'G-VPZ8G3CJ5S',
  );
}
